// eslint-disable-next-line import/no-anonymous-default-export
export const styles = {
  bg: `bg-[#0b0817] px-[18px] pt-[150px] pb-[200px] flex justify-center`,
  about1: `bg-[#0b0817] font-[Arial] text-[25px] text-center md:text-[45px] pt-[40px]`,
  purple: `font-manrope text-[25px] text-[#6e45c7] md:text-[40px]`,
  container: `bg-[#161226] border-white shadow-[1px_1px_10px_-4px_rgba(0,0,0,0)] shadow-white rounded-[30px] px-3 py-3 flex flex-col sm:flex-row justify-center md:max-w-2xl shadow-lg  `,
  div1: ` p-2 sm:w-1/2 flex flex-col justify-center text-center space-y-2`,
  div2: ` p-2 sm:w-1/2 align-middle text-center flex flex-col justify-center space-y-5` ,
  image: ` px-6 py-0 `,
  generating: `font-[Arial] text-white text-lg mx-6`,
  metamaskerror: `font-[Arial] text-sm bg-[#ffffff] mx-6 capitalize p-1`,
  btnconnect: `font-[Arial] border-0 w-full animate-pulse text-lg bg-[#6e45c7] hover:bg-[#7935adcc] text-white font-bold p-4  shadow-md`,
  btnclear: `font-[Arial] w-full text-lg bg-[#6e45c7] hover:bg-[red] text-white font-bold p-4  shadow-md border-0`,
  btnredo: `font-[Arial] w-[80px] text-lg bg-[#4b2c91] hover:bg-[grey] text-white font-bold p-4  shadow-md border-0`,
  btnQR: ` border-0 font-[Arial] w-[50px] text-lg bg-[#4b2c91] hover:bg-[grey] text-white  font-bold   shadow-md`,
  polygon: `max-w-[100px] mx-auto`,
  modal: `mx-auto`,
  spinner: `mb-2 mx-auto mt-[100px] w-20 h-20 rounded-full animate-spin border-8 border-solid border-purple-500 border-t-transparent`,
  opensea: `max-w-[260px] mx-auto pt-[20px]`,
  inputbox: `font-[Arial] w-[full] text-[18px]`,
  inputfield: `w-[100%] text-[#64B6AC] truncate`,
}